// Выполняет поиск во внутреннем массиве номера ошибки errnum и 
// возвращает указатель на строку с сообщением об ошибке. 
// Нужно объявить макросы, содержащие массивы сообщений об ошибке 
// для операционных систем mac и linux. Описания ошибок есть в оригинальной библиотеке. 
// Проверка текущей ОС осуществляется с помощью директив.

#include "s21_string.h"
#include <stdio.h>

#ifdef __APPLE__
static const char* ERROR_LIST[] = {
    "Undefined error: 0",
    "Operation not permitted",
    "No such file or directory",
    "No such process",
    "Interrupted system call",
    "Input/output error",
    "Device not configured",
    "Argument list too long",
    "Exec format error",
    "Bad file descriptor",
    "No child processes",
    "Resource deadlock avoided",
    "Cannot allocate memory",
    "Permission denied",
    "Bad address",
    "Block device required",
    "Resource busy",
    "File exists",
    "Cross-device link",
    "Operation not supported by device",
    "Not a directory",
    "Is a directory",
    "Invalid argument",
    "Too many open files in system",
    "Too many open files",
    "Inappropriate ioctl for device",
    "Text file busy",
    "File too large",
    "No space left on device",
    "Illegal seek",
    "Read-only file system",
    "Too many links",
    "Broken pipe",
    "Value too large to be stored in data type",
    "Resource temporarily unavailable",
    "Operation now in progress",
    "Operation already in progress",
    "Socket operation on non-socket",
    "Destination address required",
    "Message too long",
    "Protocol wrong type for socket",
    "Protocol not available",
    "Protocol not supported",
    "Socket type not supported",
    "Operation not supported",
    "Protocol family not supported",
    "Address family not supported by protocol family",
    "Address already in use",
    "Can't assign requested address",
    "Network is down",
    "Network unreachable",
    "Network dropped connection on reset",
    "Software caused connection abort",
    "Connection reset by peer",
    "No buffer space available",
    "Socket is already connected",
    "Socket is not connected",
    "Can't send after socket shutdown",
    "Too many references: can't splice",
    "Operation timed out",
    "Connection refused",
    "Too many levels of symbolic links",
    "File name too long",
    "Host is down",
    "No route to host",
    "Directory not empty",
    "Too many processes",
    "Too many users",
    "Disc quota exceeded",
    "Stale NFS file handle",
    "Too many levels of remote in path",
    "RPC struct is bad",
    "RPC version wrong",
    "RPC prog. not avail",
    "Program version wrong",
    "Bad procedure for program",
    "No locks available",
    "Function not implemented",
    "Inappropriate file type or format",
    "Authentication error",
    "Need authenticator",
    "Device power is off",
    "Device error",
    "Value too large to be stored in data type",
    "Bad executable (or shared library)",
    "Bad CPU type in executable",
    "Shared library code can't be changed",
    "Unknown error: 87",
    "No anode",
    "File system object is remote",
    "Required level is not supported by the security policy",
    "Invalid or incomplete multibyte or wide character",
    "Inappropriate type for ioctl",
    "Unknown error: 92",
    "Unknown error: 93",
    "Unknown error: 94",
    "Unknown error: 95",
    "Unknown error: 96",
    "Unknown error: 97",
    "Unknown error: 98",
    "Unknown error: 99",
    "Unknown error: 100",
    "Unknown error: 101",
    "Unknown error: 102",
    "Unknown error: 103",
    "Unknown error: 104",
    "Unknown error: 105",
    "Unknown error: 106"
};
#define MAX_ERROR 106
#elif __linux__
static const char* ERROR_LIST[] = {
    "Success",
    "Operation not permitted",
    "No such file or directory",
    "No such process",
    "Interrupted system call",
    "Input/output error",
    "No such device or address",
    "Argument list too long",
    "Exec format error",
    "Bad file number",
    "No child processes",
    "Resource temporarily unavailable",
    "Cannot allocate memory",
    "Permission denied",
    "Bad address",
    "Block device required",
    "Device or resource busy",
    "File exists",
    "Cross-device link",
    "No such device",
    "Not a directory",
    "Is a directory",
    "Invalid argument",
    "Too many open files in system",
    "Too many open files",
    "Inappropriate ioctl for device",
    "Text file busy",
    "File too large",
    "No space left on device",
    "Illegal seek",
    "Read-only file system",
    "Too many links",
    "Broken pipe",
    "Math argument out of domain of func",
    "Result too large",
    "Resource temporarily unavailable",
    "Operation now in progress",
    "Operation already in progress",
    "Socket operation on non-socket",
    "Destination address required",
    "Message too long",
    "Protocol wrong type for socket",
    "Protocol not available",
    "Protocol not supported",
    "Socket type not supported",
    "Operation not supported",
    "Protocol family not supported",
    "Address family not supported by protocol family",
    "Address already in use",
    "Cannot assign requested address",
    "Network is down",
    "Network is unreachable",
    "Net was reset",
    "Connection aborted",
    "Connection reset by peer",
    "No buffer space available",
    "Socket is already connected",
    "Socket is not connected",
    "Cannot send after socket shutdown",
    "Too many references: can't splice",
    "Connection timed out",
    "Connection refused",
    "Host is down",
    "No route to host",
    "Operation canceled",
    "Owner died",
    "State not recoverable",
    "No authentication data",
    "Program is not authenticated",
    "Unknown error 86",
    "Unknown error 87",
    "Unknown error 88",
    "Unknown error 89",
    "Unknown error 90",
    "Unknown error 91",
    "Unknown error 92",
    "Unknown error 93",
    "Unknown error 94",
    "Unknown error 95",
    "Unknown error 96",
    "Unknown error 97",
    "Unknown error 98",
    "Unknown error 99",
    "Unknown error 100",
    "Unknown error 101",
    "Unknown error 102",
    "Unknown error 103",
    "Unknown error 104",
    "Unknown error 105",
    "Unknown error 106",
    "Unknown error 107",
    "Unknown error 108",
    "Unknown error 109",
    "Unknown error 110",
    "Unknown error 111",
    "Unknown error 112",
    "Unknown error 113",
    "Unknown error 114",
    "Unknown error 115",
    "Unknown error 116",
    "Unknown error 117",
    "Unknown error 118",
    "Unknown error 119",
    "Unknown error 120",
    "Unknown error 121",
    "Memory page has hardware error",
    "Unknown error 123",
    "Unknown error 124",
    "Unknown error 125",
    "Unknown error 126",
    "Unknown error 127",
    "Unknown error 128",
    "Unknown error 129",
    "Unknown error 130",
    "Unknown error 131",
    "Unknown error 132",
    "No medium found"
};
#define MAX_ERROR 133
#endif

char* s21_strerror(int errnum) {
    static char buffer[100];
    char* result = buffer;
    int error_found = 0;
    
    if (errnum >= 0 && errnum <= MAX_ERROR) {
        result = (char*)ERROR_LIST[errnum];
        error_found = 1;
    }
    
    if (!error_found) {
        #ifdef __linux__
            sprintf(buffer, "Unknown error %d", errnum);
        #elif __APPLE__
            sprintf(buffer, "Unknown error: %d", errnum);
        #endif
    }
    
    return result;
}